networks:
  traefik:
    external: true

services:
  app:
    image: workouts
    container_name: workouts
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID}
        VITE_GOOGLE_API_KEY: ${VITE_GOOGLE_API_KEY}
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - traefik.http.routers.workouts.rule=Host(`workouts.whitney.rip`)
      - traefik.http.routers.workouts.tls=true
      - traefik.http.routers.workouts.tls.certresolver=lets-encrypt
      - traefik.http.services.workouts.loadbalancer.server.port=80
      - traefik.port=80
